### ISSUE TITLE
Corrupted graphics, misplaced objects

### ISSUE THREAD

**Issue by kcowolf** [cuckydev/SoniCPort#1]
I'm using Visual Studio 2019, SDL2-2.0.14 (https://www.libsdl.org/release/SDL2-devel-2.0.14-VC.zip), and I have commit 5650a16650324a8d5b1392260e49d82019e681bb checked out.

I run the following command to build the solution:
`cmake -B build -DCMAKE_BUILD_TYPE=Release -DBACKEND=SDL2 -DMSVC_LINK_STATIC_RUNTIME=ON -DSDL2_DIR=[path]\SDL2-2.0.14`

I then open the .sln file in VS2019, build (x64, Debug or Release made no difference) and run.  The graphics are corrupted as shown.

In the third screenshot, Sonic is standing on solid terrain.  The bridge next to him works if he stands on it, but it's not over a gap as intended.

![Gfx corruption 1](https://user-images.githubusercontent.com/23274338/108589389-ac7f3700-7323-11eb-9959-2d2c3fb11993.png)
![Gfx corruption 2](https://user-images.githubusercontent.com/23274338/108589385-abe6a080-7323-11eb-8b88-ffbfcf3ce09c.png)
![Gfx corruption 3](https://user-images.githubusercontent.com/23274338/108589386-abe6a080-7323-11eb-8dbf-c611ae0dc709.png)
![Gfx corruption 4](https://user-images.githubusercontent.com/23274338/108589388-ac7f3700-7323-11eb-8512-3551c5b85aa8.png)

**Comment by cuckydev** [comment]
I have no idea what the hell happened here? I've only ever compiled using GCC, but I hadn't imagined that MSVC would somehow screw it up this bad.

**Comment by cuckydev** [comment]
To add on, I believe I can see the specific issues here. Object mappings aren't being applied properly, which is why all objects with more than 1 sprite piece (Sonic, Title Sonic, etc.) are kind of garbled. Planes just aren't referencing the correct data. However, the misplaced objects? No idea. The only way things can be this screwed up is if MSVC manages to fail to compile basic bitwise operations.

**Comment by kcowolf** [comment]
I got mingw-w64 installed and built SoniCPort with it, and it works, so this is definitely specific to MSVC.

**Comment by deltaphc** [comment]
While I don't have any specific knowledge of what's wrong here, usually when this sort of thing happens, it's a sign that you might be running into Undefined Behavior, i.e. something that's semantically invalid in C, or you're managing memory wrong, or maybe there's an uninitialized variable somewhere, etc. This all tends to cause code to miscompile especially when optimizations are turned on.

One way to test would be to try a Debug build (or otherwise a build with `-O0` to turn off optimizations), and see if things change.

**Comment by cuckydev** [comment]
Well, Clownacy brought it to my attention that I never implemented the ALIGN macros for MSVC.. should look into that.

**Comment by kcowolf** [comment]
Fix works great, thanks! 👍
